version: "2"

services: 
  gf:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - 8765:8765
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports: 
      - 80:80
    volumes: 
      - ./src/frontend/:/usr/share/nginx/html

      

